apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/iadocicco-ale/aula-gitops.git
    path: argocd
    targetRevision: HEAD
    directory:
      recurse: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  syncWindows:
  - kind: allow
    timeZone: "Europe/Rome"
    schedulle: '0 9 * * *'
    duration: 12h
    applications:
    - '*'
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
