apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: default
  namespace: argocd
spec:
  description: Projeto padrão com restrição de janela de sync
  sourceRepos:
    - '*'
  destinations:
    - namespace: '*'
      server: '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  syncWindows:
    - kind: allow
      schedule: "0 9-20 * * *"   # abre de 09:00 até 20:59 todos os dias
      duration: 1h               # cada janela dura 1h
      applications:
        - "*"
      timeZone: "Europe/Rome"