apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: webcolor
  namespace: argocd
  labels:
    curso: gitops
spec:
  project: default
  source:
    repoURL: https://github.com/iadocicco-ale/web-page-deploy.git
    path: k8s
    targetRevision: HEAD
    directory:
      recurse: true
      include: 'deployment.yaml'
  syncPolicy:
    automated: {}
  destination:
    namespace: webcolor
    server: https://kubernetes.default.svc
  info:
    - name: Projeto
      value: "Curso GitOps"
