apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: conversao
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/iadocicco-ale/web-page-deploy.git
    targetRevision: HEAD
    path: kustomize
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  destination:
    namespace: conversao
    server: https://kubernetes.default.svc